fails with pioarduino 3.0.3 which is based on ESP-IDF 5.1.4:
src/SSLCert.cpp: In function 'int httpsserver::cert_write(SSLCert&, std::string, std::string, std::string)':
src/SSLCert.cpp:184:33: error: too few arguments to function 'int mbedtls_pk_parse_key(mbedtls_pk_context*, const unsigned char*, size_t, const unsigned char*, size_t, int (*)(void*, unsigned char*, size_t), void*)'
  184 |   stepRes = mbedtls_pk_parse_key( &key, certCtx.getPKData(), certCtx.getPKLength(), NULL, 0 );
      |             ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/SSLCert.hpp:11,
                 from src/SSLCert.cpp:1:
/Users/mah/.platformio/packages/framework-arduinoespressif32-libs/esp32s3/include/mbedtls/mbedtls/include/mbedtls/pk.h:1101:5: note: declared here
 1101 | int mbedtls_pk_parse_key(mbedtls_pk_context *ctx,
      |     ^~~~~~~~~~~~~~~~~~~~
esptool.py v4.7.5
Creating esp32s3 image...
Merged 1 ELF section
Successfully created esp32s3 image.
src/SSLCert.cpp:233:13: error: 'mbedtls_x509write_crt_set_serial' was not declared in this scope; did you mean 'mbedtls_x509write_crt_set_version'?
  233 |   stepRes = mbedtls_x509write_crt_set_serial( &crt, &serial );
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |             mbedtls_x509write_crt_set_version
Generating partitions .pio/build/custom-server/partitions.bin
*** [.pio/build/custom-server/src/SSLCert.cpp.o] Error 1